#!/bin/bash 

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/ceph/

cd tests 
ln -s /usr/lib64/ceph/libceph-common.so.2 lib/libceph-common.so.2
#pip3 install virtualenv  -i https://pypi.tuna.tsinghua.edu.cn/simple
