#!/bin/bash 


PATH=$PATH:/usr/libexec/git-core

export PERL5LIB=/usr/share/perl5/

#skip t3434 case for ISO-2022-JP.so
export GIT_SKIP_TESTS="t3434.3 t3434.6 t3900.17 t3900.25 t3900.27 t3900.28 t3900.29 t3900.37 t3900.38"

#error: cannot convert from ISO-2022-JP to UTF-8
export GIT_SKIP_TESTS="$GIT_SKIP_TESTS t5100.5"
export GIT_SKIP_TESTS="$GIT_SKIP_TESTS t5100.24"
export GIT_SKIP_TESTS="$GIT_SKIP_TESTS t8005.2 t8005.3 t8005.4"

#no tkiff tools for yocto
export GIT_SKIP_TESTS="$GIT_SKIP_TESTS t7800.28"

#no iso-8859-7 
export GIT_SKIP_TESTS="$GIT_SKIP_TESTS t9300.193 t9350.9"
export GIT_SKIP_TESTS="$GIT_SKIP_TESTS t9350.26 t9350.27 t9350.43"
export GIT_SKIP_TESTS="$GIT_SKIP_TESTS t9350.44"

#Some of the tools only work in a windowed
#environment.If run in a terminal-only session, they will fail.
export GIT_SKIP_TESTS="$GIT_SKIP_TESTS t7610.28"

cd tests/t

prove --timer --jobs 15 ./t[0-9]*.sh
